# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Pipeline Merge

on:
  push:
    branches: [ "main" ]

jobs:
  code_build:
    name: Code build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Building with ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Build application
      run: npm run build --if-present

  unit_test:
    name: Unit testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Testing with ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Execute unit testing
      run: echo "Test"

  static_code_analysis:
    name: Static code analysis
    needs: [code_build, unit_test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Static code analysis with ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Code analysis
      run: echo "Static code analysis"

    name: Deploy to development
    needs: generate_artifact
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: 'RGEUK8S' 
          cluster-name: 'demok8s'
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          namespace: 'development'
          manifests: |
             k8s-manifest/deployment.yaml
             k8s-manifest/ingress-dev.yaml
             k8s-manifest/service.yaml
          images: 'rcronald/block-master:main'
          pull: false